import type { InkMode, Vertical, Composition, GenerationStatus } from '@/types/database';

export const DEFAULT_STYLE_BLOCK = `Hand-drawn editorial ink illustration with confident, gestural brushpen linework. Black ink on white paper. Variable line weight: heavier strokes on outer contours of bodies and large furniture forms (3-4px weight), lighter strokes on interior details like facial features, fingers, screen contents, and small objects (1-1.5px weight). The transition between thick and thin happens organically within single strokes, like pressure variation on a real brush pen. Lines are organic and slightly imperfect — not digitally precise, not deliberately wobbly. Strokes occasionally trail off and don't fully close at edges, suggesting editorial confidence. Human figures have approximately 1:5.5 head-to-body ratio with hair as the primary distinguishing feature between characters (render hair with care: wavy parallel strokes, solid black mass, bun shapes, tight curls, straight strands — no two figures should have identical hair). Faces have simple dot or line eyes, a minimal line nose, and an optional line mouth. Hands show 3-4 fingers in quick gestural shorthand. Clothing is drawn as silhouette contours with minimal interior line — no buttons, no patterns, no fabric texture. Furniture and objects are recognizable from their outline only, with no interior fill. Plants appear as quick leaf shapes in simple pots, always in black line. The drawing quality specifically suggests a Pentel Pocket Brush Pen or Faber-Castell Pitt Artist Pen on smooth cartridge paper. The overall impression should be: this looks like it was drawn by a skilled editorial illustrator for Monocle magazine or The New Yorker in about 15 minutes — confident, warm, human, with the hand visible in every stroke.`;

export const DEFAULT_EXCLUSIONS_BLOCK = `No gradients. No drop shadows. No cast shadows. No ambient occlusion. No glow effects. No 3D rendering. No photorealistic elements. No smooth uniform-weight digital vector lines. No filled backgrounds behind the full scene. No detailed patterns on clothing (no plaid, polka dots, florals, stripes). No wood grain or fabric texture on furniture. No text in the illustration unless specifically requested. No watermarks or signatures. The illustration must look hand-drawn by a human, not generated by AI or rendered in a vector program. Avoid bilateral symmetry. Avoid geometric precision in organic forms — a table should look sketched, not CAD-drafted.`;

export const INK_MODE_LABELS: Record<InkMode, string> = {
  pure_ink: 'Pure Ink',
  single_register: 'Single Register',
  double_register: 'Double Register',
  tinted_mono: 'Tinted Monochrome',
};

export const INK_MODE_DESCRIPTIONS: Record<InkMode, string> = {
  pure_ink: 'All black ink on white. No colour. Solid black fills only for hair and clothing emphasis.',
  single_register: 'Black ink + ONE accent colour as flat fill on max 20% of area.',
  double_register: 'Black ink + TWO accent colours. Primary 15%, secondary 10%.',
  tinted_mono: 'No black ink. Entire linework in a single dark brand colour. Duotone effect.',
};

export const VERTICAL_LABELS: Record<Vertical, string> = {
  space: 'Space',
  people: 'People',
  tech: 'Tech',
  master: 'Master',
  custom: 'Custom',
};

export const COMPOSITION_LABELS: Record<Composition, string> = {
  centered_vignette: 'Centered Vignette',
  environmental: 'Environmental Scene',
  isometric: 'Isometric Room',
  cropped: 'Cropped Frame',
  grid: 'Grid Portrait',
};

export const COMPOSITION_DESCRIPTIONS: Record<Composition, string> = {
  centered_vignette: 'Figure group centred with white space on all sides. No background. Objects float.',
  environmental: 'Figures within a described space, architectural lines suggesting walls/ceiling/floor.',
  isometric: 'Deliberate isometric perspective showing room from above-corner angle. Coloured wall planes.',
  cropped: 'Figures partially cut off by frame edges, intimate "caught mid-action" feel.',
  grid: 'Multiple separate frames arranged in a grid, each with a different person.',
};

export const SUBJECT_SUGGESTIONS: Record<string, string[]> = {
  workspace: [
    'Open plan office with hot desks and a central communal table',
    'Private cabin with glass walls, one person working inside',
    'Phone booth pod with person on a call, laptop on small shelf',
    'Reception area with welcome desk, visitor signing in',
    'Office pantry/kitchen with person making coffee, another leaning on counter chatting',
    'Large meeting room with long table, chairs, wall-mounted screen',
    'Hot desk area with multiple people working at shared long desks',
    'Lounge/breakout zone with sofas, coffee table, two people in conversation',
    'Server room with racks of equipment, cables, blinking lights',
    'Rooftop terrace with outdoor furniture, plants, city skyline hint',
    'Co-working space with diverse people at individual stations',
    'Corner office with large desk, bookshelf, window view',
    'Library/quiet zone with reading nooks and focused workers',
  ],
  people: [
    'Team meeting with 4-6 people around a table, one presenting',
    'Video call with person at desk facing laptop camera, remote faces on screen',
    'One-on-one conversation between two people at a small table',
    'Person at desk working on laptop, coffee cup nearby',
    'Presentation at whiteboard, speaker gesturing, audience seated',
    'New employee onboarding, welcome handshake or badge exchange',
    'Job interview, two people across a table, one taking notes',
    'Coffee break chat, two people standing with mugs in a pantry',
    'Collaborative brainstorm around a table with sticky notes',
    'Person walking through office with laptop under arm',
    'Group of people in an elevator, casual conversation',
    'Person standing at a standing desk, stretching',
    'Mentor and mentee walking through an office corridor',
  ],
  technology: [
    'Wall-mounted display showing video conference with AV controls below',
    'Video conferencing setup with camera, microphone array, and large screen',
    'Person adjusting a mounted screen or camera angle in a meeting room',
    'Laptop and tablet side by side on a clean desk',
    'Smart room control panel on wall, person tapping to adjust settings',
    'Cable management rack in server room, technician working',
    'Person wearing headphones and speaking into microphone at desk',
    'Interactive touchscreen kiosk in a lobby, person navigating',
    'Wireless presentation dongle being plugged into a laptop',
    'Digital signage in hallway showing announcements',
    'Person scanning QR code to book a meeting room',
  ],
  events: [
    'Company anniversary celebration with cake, balloons, group gathered',
    'Town hall meeting in a large room, CEO on stage, audience seated',
    'Workshop/training session with facilitator at flip chart',
    'Networking event with people standing in groups, drinks in hand',
    'Panel discussion with 3-4 speakers on a stage, moderator',
    'Award ceremony with person receiving trophy, audience applauding',
    'Team offsite in a casual outdoor setting, activities',
    'Product launch event with presentation screen and audience',
    'Holiday party in decorated office space',
    'Hackathon with teams at tables, laptops, whiteboards',
  ],
  'brand applications': [
    'Business card with ink illustration as decorative element',
    'Tote bag with ink illustration printed on one side',
    'Website hero section showing ink illustration as banner',
    'Annual report cover with full-bleed ink illustration',
    'Presentation slide template with ink illustration border',
    'Email signature with small ink illustration icon',
    'Social media post template with ink illustration background',
  ],
  abstract: [
    'Abstract composition of overlapping geometric shapes with ink linework',
    'Pattern of repeating office objects: coffee cups, laptops, chairs, plants',
    'Cityscape silhouette with ink-drawn buildings and architectural details',
    'Collection of hand-drawn icons: wifi, coffee, lightbulb, handshake, clock',
    'Decorative border or frame made of ink-drawn office elements',
    'Map-style illustration of an office floor plan from above',
  ],
};

export const VERTICAL_BADGE_VARIANT: Record<Vertical, 'amber' | 'coral' | 'cobalt' | 'default'> = {
  space: 'amber',
  people: 'coral',
  tech: 'cobalt',
  master: 'default',
  custom: 'default',
};

export const STATUS_BADGE_VARIANT: Record<GenerationStatus, 'success' | 'warning' | 'default'> = {
  approved: 'success',
  rejected: 'warning',
  pending: 'default',
};

export const DEFAULT_PALETTE = {
  name: 'INNOVA Primary',
  core_dark: '#191919',
  core_light: '#FAF7F3',
  vertical_space_name: 'Cinnamon',
  vertical_space_hex: '#D4772E',
  vertical_people_name: 'Twilight',
  vertical_people_hex: '#2D4272',
  vertical_tech_name: 'Hunter',
  vertical_tech_hex: '#3D6B4F',
};
